// Mocks generated by Mockito 5.4.5 from annotations
// in taste_master_app/test/cubit/api_tests/api_dog_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:taste_master_app/src/data/models/models.dart' as _i4;
import 'package:taste_master_app/src/data/repositories/dogs/dogs_repository.dart'
    as _i2;
import 'package:taste_master_app/src/data/repositories/exceptions/fetch_data_exception.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [DogsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDogsRepository extends _i1.Mock implements _i2.DogsRepository {
  MockDogsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> fetchAllDogs(
    Map<String, String>? params,
    dynamic Function(List<_i4.ApiDogModel>)? data,
    dynamic Function(_i5.FetchDataException)? exception,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchAllDogs,
          [
            params,
            data,
            exception,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> searchDogs(
    String? query,
    dynamic Function(List<_i4.ApiDogModel>)? data,
    dynamic Function(_i5.FetchDataException)? exception,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchDogs,
          [
            query,
            data,
            exception,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
